### ISSUE TITLE
ospd-openvas pip package is not up to date and contains a bug

### ISSUE THREAD

**Issue by spellanser** [greenbone/ospd-openvas#338]
Last pip package update: August, 12 - https://pypi.org/project/ospd-openvas/

@jjnicola have fixed the bug on August 13: https://github.com/greenbone/ospd-openvas/commit/9ff3e0cdeb066721ed649101b2de6d7ac8800a8c

The pip package still contains the bug fixed in that commit.

Error associated with the bug:
`ospd_openvas.errors.OspdOpenvasError: Error setting nvticache. Incompatible nvticache version 20.8.0~git-a03eec19-HEAD. Supported versions are >=11.0.`

**Comment by jjnicola** [comment]
Hi @spellanser,
as you already noticed, the bug was patched with the PR #317 and it will be included in the next ospd-openvas-20.08 patch release.  Once released, the new package will be upload to PyPI. A better channel to ask about new releases and keep informed is https://community.greenbone.net/. As the bug has been already fixed, I am closing the issue here.

**Comment by spellanser** [comment]
OK. I just reported, that current ospd-openvas==20.08 pip package contains that bug, and can't be used. 
Note for others, who encounter this problem: clone repository and use the 20.08 branch to install locally from cloned repository:
1. `git clone --single-branch --branch ospd-openvas-20.08 https://github.com/greenbone/ospd-openvas.git`
2. `pip3 install <path_to_cloned_repo>/ospd-openvas`
