### ISSUE TITLE
[22.4.0] Test test_port_convert fails

### ISSUE THREAD

**Issue by tuxmaster5000** [greenbone/ospd-openvas#696]
The test tests/test_port_convert.py fails with:
==================================== ERRORS ====================================
_________________ ERROR collecting tests/test_port_convert.py __________________
tests/test_port_convert.py:46: in <module>
    logging.disable()
E   TypeError: disable() missing 1 required positional argument: 'level'
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.30 seconds ============================
Reading the python doc's:
https://docs.python.org/3/library/logging.html#module-logging
It will requires an options.

**Comment by tuxmaster5000** [comment]
change the line to logging.disable(logging.CRITICAL) will work,

**Comment by Kraemii** [comment]
The default was set to logging.CRITICAL since python 3.7 https://github.com/python/cpython/issues/72710
We do not support any python version lower than 3.7, that is also the reason the test do not fail within our pipeline.

**Comment by sukurocking** [comment]
I understand that in the [Requirements](https://github.com/greenbone/ospd-openvas#requirements) section of the [README.md](https://github.com/greenbone/ospd-openvas#readme) documentation, it is specified that Python 3.7 and later is supported. 
As @Kraemii  pointed out, `logging.CRITICAL` is set to default since Python 3.7.

Hence, the issue should not be in open state. 
Suggest the issue be marked as closed, making it convenient for other contributors.

**Comment by jjnicola** [comment]
Hello @tuxmaster5000! Since we don't support lower versions than 3.7, I am closing the issue. Reasons explained above.

**Comment by jjnicola** [comment]
Reopen after internal discussion. This doesn't mean that we support older python versions.
